#!/bin/bash
# Author: wswenyue.
# Date & Time: 2018-11-05 18:59:31
# Description: a bash script
AK_DIR=exe_path
if [ "$AK_DIR" = "exe_path" ]; then
	AK_DIR="$(cd "$(dirname "$0")" && pwd)"
fi

has(){
    type "$1" > /dev/null 2>&1
}

if has "python3"; then
	PYTHONPATH="${AK_DIR}/src" python3 -m aklog "$@"
elif has "python"; then
	PYTHONPATH="${AK_DIR}/src" python -m aklog "$@"
else
	echo >&2 "Failed to execute, please install python before."
fi
