#!/bin/bash
# Sync release version into build_meta.py and pyproject.toml.
# Usage: scripts/sync-version.sh vX.Y.Z
set -euo pipefail

GIT_TAG="${1:?Usage: $0 vX.Y.Z}"
if [[ ! "$GIT_TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "Invalid tag format (expected vX.Y.Z): $GIT_TAG" >&2
  exit 1
fi

VERSION="${GIT_TAG#v}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

GIT_SHA="$(git rev-parse --short HEAD)"

cat > src/aklog/build_meta.py <<EOF
# Generated by scripts/sync-version.sh — do not edit by hand.
GIT_TAG = "${GIT_TAG}"
__version__ = "${VERSION}"
GIT_SHA = "${GIT_SHA}"
EOF

python3 <<PY
from pathlib import Path
import re

path = Path("pyproject.toml")
text = path.read_text(encoding="utf-8")
if re.search(r'^version\\s*=', text, re.M):
    text = re.sub(r'^version\\s*=\\s*".*"', 'version = "${VERSION}"', text, count=1, flags=re.M)
else:
    text = text.replace(
        "[project]",
        '[project]\\nversion = "${VERSION}"',
        1,
    )
path.write_text(text, encoding="utf-8")
PY

echo "Synced version ${GIT_TAG} (sha ${GIT_SHA})"
